// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIPayement.Models;

namespace WebAPIPayement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190516172140_addTables")]
    partial class addTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebAPIPayement.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("WebAPIPayement.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CateroryId");

                    b.Property<string>("Designation")
                        .IsRequired();

                    b.Property<string>("Photo")
                        .IsRequired();

                    b.Property<double>("Price");

                    b.Property<int>("Stock");

                    b.HasKey("ArticleId");

                    b.HasIndex("CateroryId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("WebAPIPayement.Models.Category", b =>
                {
                    b.Property<int>("CateroryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("CateroryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WebAPIPayement.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WebAPIPayement.Models.Command", b =>
                {
                    b.Property<int>("CommandId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ArticleId");

                    b.Property<int?>("ClientId");

                    b.Property<DateTime>("CommandDate");

                    b.Property<int>("Quantity");

                    b.HasKey("CommandId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ClientId");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("WebAPIPayement.Models.PayementDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<string>("CardNumber")
                        .IsRequired();

                    b.Property<string>("CardOwnerName")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("ExpirationDate")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("PayementDetails");
                });

            modelBuilder.Entity("WebAPIPayement.Models.Article", b =>
                {
                    b.HasOne("WebAPIPayement.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CateroryId");
                });

            modelBuilder.Entity("WebAPIPayement.Models.Command", b =>
                {
                    b.HasOne("WebAPIPayement.Models.Article", "Article")
                        .WithMany("Commands")
                        .HasForeignKey("ArticleId");

                    b.HasOne("WebAPIPayement.Models.Client", "Client")
                        .WithMany("Commands")
                        .HasForeignKey("ClientId");
                });
#pragma warning restore 612, 618
        }
    }
}
