// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIPayement.Models;

namespace WebAPIPayement.Migrations
{
    [DbContext(typeof(PayementDbContext))]
    partial class PayementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebAPIPayement.Models.PayementDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CVV");

                    b.Property<string>("CardNumber");

                    b.Property<string>("CardOwnerName");

                    b.Property<string>("ExpirationDate");

                    b.HasKey("Id");

                    b.ToTable("PayementDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
